language: cpp

compiler:
  - gcc

os:
  - linux

before_install:
  - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha9/premake-5.0.0-alpha9-linux.tar.gz
  - tar -zxf premake-5.0.0-alpha9-linux.tar.gz
  - sudo apt-get update && sudo apt-get install -y --no-install-recommends libsfml-dev libglew-dev libassimp-dev libbullet*

script:
  - ls
  - cp premake5 Pyros3D && cd Pyros3D
  - premake5 --x64 --examples gmake
  - cd build && make