language: cpp

compiler:
  - gcc

os:
  - linux

before_install:
  - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha9/premake-5.0.0-alpha9-linux.tar.gz
  - tar -zxf premake-5.0.0-alpha9-linux.tar.gz
  - ldd premake5
  - sudo apt-get update -qq && sudo apt-get install -y --no-install-recommends libc6-dev libsfml-dev libglew-dev libassimp-dev libbullet*

script:
  - ./premake5 --x64 --examples gmake
  - cd build && make