language: cpp

compiler:
  - gcc

os:
  - linux

before_install:
  sudo add-apt-repository -y ppa:codegear/release && sudo apt-get update -qq && sudo apt-get install -y --no-install-recommends libsfml-dev libglew-dev libbullet-dev premake5

script:
  - premake5 --x64 --examples gmake
  - cd build && make