sudo: required

dist: trusty

language: cpp

compiler:
  - gcc

os:
  - linux

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes libfreetype6-dev libassimp-dev libbullet-dev libsdl2-dev libstdc++6 libpthread-stubs0-dev libgl1-mesa-dev libx11-dev libxrandr-dev libfreetype6-dev libglew1.5-dev libjpeg8-dev libsndfile1-dev libopenal-dev libudev-dev libxcb-image0-dev libjpeg-dev libflac-dev

script:
  - make build
  - cd build
  - cmake -DIS_DESKTOP=ON -DOPENGL_VERSION=GL45 -DCONTEXT=SDL2 -DBUILD_DEMOS=ON -DBUILD_CONVERTER=ON ..
  - make
