#if defined(_RotatingCube)
#include "RotatingCube/RotatingCube.h"
#elif defined(_MSAATest)
#include "MSAATest/MSAATest.h"
#elif defined(_SkyboxTest)
#include "SkyboxTest/SkyboxTest.h"
#elif defined(_RotatingTexturedCube)
#include "RotatingTexturedCube/RotatingTexturedCube.h"
#elif defined(_RotatingTextureAnimatedCube)
#include "RotatingTextureAnimatedCube/RotatingTextureAnimatedCube.h"
#elif defined(_RotatingCubeWithLighting)
#include "RotatingCubeWithLighting/RotatingCubeWithLighting.h"
#elif defined(_RotatingCubeWithStencilReflections)
#include "RotatingCubeWithStencilReflections/RotatingCubeWithStencilReflections.h"
#elif defined(_RotatingCubeWithLightingAndShadow)
#include "RotatingCubeWithLightingAndShadow/RotatingCubeWithLightingAndShadow.h"
#elif defined(_CustomMaterial)
#include "CustomMaterial/CustomMaterial.h"
#elif defined(_PickingPainterMethod)
#include "PickingPainterMethod/PickingPainterMethod.h"
#elif defined(_DeferredRendering)
#include "DeferredRendering/DeferredRendering.h"
#elif defined(_TextRendering)
#include "TextRendering/TextRendering.h"
#elif defined(_SkeletonAnimationExample)
#include "SkeletonAnimationExample/SkeletonAnimationExample.h"
#elif defined(_SimplePhysics)
#include "SimplePhysics/SimplePhysics.h"
#elif defined(_RacingGame)
#include "RacingGame/RacingGame.h"
#elif defined(_LOD_Example)
#include "LOD_Example/LOD_Example.h"
#elif defined(_IslandDemo)
#include "IslandDemo/IslandDemo.h"
#elif defined(_Cubeland)
#include "Cubeland/Cubeland.h"
#elif defined(_Decals)
#include "Decals/Decals.h"
#elif defined(_ImGuiExample)
#include "ImGuiExample/ImGuiExample.h"
#elif defined(_DepthOfField)
#include "DepthOfField/DepthOfField.h"
#elif defined(_SSAOExample)
#include "SSAOExample/SSAOExample.h"
#elif defined(_LuaScripting)
#include "LuaScripting/LuaScripting.h"
#elif defined(_SceneSerializationExample)
#include "SceneSerializationExample/SceneSerializationExample.h"
#elif defined(_MotionBlur)
#include "MotionBlur/MotionBlur.h"
#elif defined(_ParallaxMapping)
#include "ParallaxMapping/ParallaxMapping.h"
#elif defined(_ParticlesExample)
#include "ParticlesExample/ParticlesExample.h"
#elif defined(_MotionBlurExample)
#include "MotionBlurExample/MotionBlurExample.h"
#elif defined(_ScreenSpaceReflection)
#include "ScreenSpaceReflection/ScreenSpaceReflection.h"
#elif defined(_LightPriorityExample)
#include "LightPriorityExample/LightPriorityExample.h"
#elif defined(_ArenaFPS)
#include "ArenaFPS/ArenaFPS.h"
#elif defined(_PBRSpheres)
#include "PBRSpheres/PBRSpheres.h"
#elif defined(_DeferredPBRSpheres)
#include "DeferredPBRSpheres/DeferredPBRSpheres.h"
#elif defined(_SSRTest)
#include "SSRTest/SSRTest.h"
#elif defined(_DemoLauncher)
#include "DemoLauncher/DemoLauncher.h"
#endif
