#if defined(_RotatingCube)
#include "RotatingCube/RotatingCube.h"
#elif defined(_RotatingTexturedCube)
#include "RotatingTexturedCube/RotatingTexturedCube.h"
#elif defined(_RotatingTextureAnimatedCube)
#include "RotatingTextureAnimatedCube/RotatingTextureAnimatedCube.h"
#elif defined(_RotatingCubeWithLighting)
#include "RotatingCubeWithLighting/RotatingCubeWithLighting.h"
#elif defined(_RotatingCubeWithStencilReflections)
#include "RotatingCubeWithStencilReflections/RotatingCubeWithStencilReflections.h"
#elif defined(_RotatingCubeWithLightingAndShadow)
#include "RotatingCubeWithLightingAndShadow/RotatingCubeWithLightingAndShadow.h"
#elif defined(_CustomMaterial)
#include "CustomMaterial/CustomMaterial.h"
#elif defined(_PickingPainterMethod)
#include "PickingPainterMethod/PickingPainterMethod.h"
#elif defined(_DeferredRendering)
#include "DeferredRendering/DeferredRendering.h"
#elif defined(_TextRendering)
#include "TextRendering/TextRendering.h"
#elif defined(_SkeletonAnimationExample)
#include "SkeletonAnimationExample/SkeletonAnimationExample.h"
#elif defined(_SimplePhysics)
#include "SimplePhysics/SimplePhysics.h"
#elif defined(_RacingGame)
#include "RacingGame/RacingGame.h"
#elif defined(_LOD_example)
#include "LOD_example/LOD_example.h"
#endif