# Engine source lists. Expects backend variables (GL_INCLUDE, SPIRV_*, VULKAN_*, IMGUI_*).

set(AUDIO_SOURCE
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Ext/miniaudio/miniaudio_impl.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Audio/AudioManager.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Audio/AudioBus.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Audio/AudioEffectChain.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Audio/Sound.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Audio/AudioSource.cpp
)

set(PYROS_ENGINE_SOURCE
	${AUDIO_SOURCE}
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/CrashHandler/CrashHandler.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/Thread/Thread.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/ModelLoaders/MultiModelLoader/ModelLoader.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/ModelLoaders/MultiModelLoader/AnimationLoader.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/ModelLoaders/IModelLoader.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/Mouse3D/Mouse3D.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/Mouse3D/PainterPick.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/Bindings/PyrosBindings.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/Bindings/PyrosLuaHelpers.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/Bindings/PyrosLuaEnums.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/Bindings/PyrosLuaMath.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/Bindings/PyrosLuaCore.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/Bindings/PyrosLuaRender.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/Bindings/PyrosLuaAssets.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/Bindings/PyrosLuaPhysics.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/Bindings/PyrosLuaPostFX.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/Bindings/PyrosLuaAudio.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/Bindings/PyrosLuaMisc.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/Bindings/PyrosLuaUI.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/Serialization/SceneSerializer.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/Geometry/Geometry.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/FPS/FPS.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/DeltaTime/DeltaTime.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/Profiler/FrameProfiler.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/Components/Lights/ILightComponent.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/Components/Lights/PointLight/PointLight.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/Components/Lights/DirectionalLight/DirectionalLight.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/Components/Lights/SpotLight/SpotLight.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/Components/Rendering/RenderingComponent.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/Components/Rendering/RenderingInstancedComponent.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/Components/Particles/ParticleSystem.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/Culling/Culling.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/Culling/FrustumCulling/FrustumCulling.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/PostEffects/PostEffectsManager.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/PostEffects/Effects/IEffect.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/PostEffects/Effects/BlurSSAOEffect.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/PostEffects/Effects/VignetteEffect.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/PostEffects/Effects/BlurXEffect.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/PostEffects/Effects/ResizeEffect.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/PostEffects/Effects/BlurYEffect.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/PostEffects/Effects/BloomEffect.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/PostEffects/Effects/RTTDebug.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/PostEffects/Effects/SSAOEffect.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/PostEffects/Effects/SSAOCompositeEffect.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/PostEffects/Effects/ScreenSpaceReflectionEffect.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/PostEffects/Effects/MotionBlurEffect.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/PostEffects/Effects/TonemapEffect.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/PostEffects/Effects/GammaEncodeEffect.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/PostEffects/Effects/DisplayTextureEffect.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/PostEffects/Effects/DepthOfFieldEffect.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/Renderer/SpecialRenderers/CubemapRenderer/CubemapRenderer.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/Renderer/SpecialRenderers/VelocityRenderer/VelocityRenderer.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/Renderer/SpecialRenderers/UIRenderer/UIRenderer.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/Components/UI/UIRect.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/Components/UI/UICanvas.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/Components/UI/UIImage.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/Components/UI/UIText.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/Components/UI/UIButton.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/Components/UI/UIBatcher.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/Components/UI/UIToggle.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/Components/UI/UISlider.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/Components/UI/UIInput.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/Components/UI/UIList.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/Components/UI/UIDropdown.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/Renderer/DebugRenderer/DebugRenderer.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/Renderer/DeferredRenderer/DeferredRenderer.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/Renderer/ForwardRenderer/ForwardRenderer.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/Renderer/IRenderer.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/Device/GLRenderDevice.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Rendering/Device/IRenderDevice.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/GameObjects/GameObject.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Core/Octree/Octree.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Core/Logs/Log.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Core/Buffers/FrameBuffer.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Core/Buffers/GeometryBuffer.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Core/InputManager/InputManager.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Core/Math/Matrix.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Core/Math/Math.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Core/Math/Easing.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Core/Math/Vec4.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Core/Math/Quaternion.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Core/Math/Vec2.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Core/Math/Vec3.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Core/Math/Random.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Core/Context/Context.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Core/Projection/Projection.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Materials/Shaders/Shaders.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Materials/IMaterial.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Materials/GenericShaderMaterials/GenericShaderMaterial.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Materials/CustomShaderMaterials/CustomShaderMaterial.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/SceneGraph/SceneGraph.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Ext/StringIDs/CRC32.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Ext/StringIDs/StringID.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Physics/Components/TriangleMesh/PhysicsTriangleMesh.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Physics/Components/Capsule/PhysicsCapsule.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Physics/Components/Cone/PhysicsCone.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Physics/Components/Sphere/PhysicsSphere.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Physics/Components/Cylinder/PhysicsCylinder.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Physics/Components/Box/PhysicsBox.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Physics/Components/ConvexTriangleMesh/PhysicsConvexTriangleMesh.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Physics/Components/IPhysicsComponent.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Physics/Components/MultipleSphere/PhysicsMultipleSphere.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Physics/Components/Vehicle/PhysicsVehicle.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Physics/Components/StaticPlane/PhysicsStaticPlane.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Physics/Components/ConvexHull/PhysicsConvexHull.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Physics/Physics.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Physics/PhysicsEngines/Box3D/DebugDraw/PhysicsDebugDraw.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Physics/PhysicsEngines/Box3D/Box3DPhysics.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Physics/PhysicsEngines/IPhysics.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Resources/Resources.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/AnimationManager/Components/IKComponent.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/AnimationManager/IKSolver.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/AnimationManager/RigAsset.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/AnimationManager/SkeletonAnimation.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/AnimationManager/TextureAnimation.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Assets/Font/Font.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Assets/Renderable/Models/Model.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Assets/Renderable/Decals/Decals.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Assets/Renderable/Renderables.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Assets/Renderable/Text/Text.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Assets/Renderable/Primitives/Primitive.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Assets/Renderable/Primitives/Shapes/Capsule.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Assets/Renderable/Primitives/Shapes/Cube.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Assets/Renderable/Primitives/Shapes/Cone.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Assets/Renderable/Primitives/Shapes/Sphere.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Assets/Renderable/Primitives/Shapes/TorusKnot.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Assets/Renderable/Primitives/Shapes/Torus.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Assets/Renderable/Primitives/Shapes/Plane.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Assets/Renderable/Primitives/Shapes/Cylinder.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Assets/Renderable/Terrains/Terrain.cpp
	${CMAKE_SOURCE_DIR}/src/Pyros3D/Assets/Texture/Texture.cpp
	${GL_INCLUDE}
	${SPIRV_TOOLING_SOURCE}
	${VULKAN_BACKEND_SOURCE}
	${METAL_BACKEND_SOURCE}
	${IMGUI_CORE_SOURCE}
)

# File I/O: Android loads from the APK via SDL_RWops; everyone else uses fopen.
if (ANDROID)
	list(APPEND PYROS_ENGINE_SOURCE
		${CMAKE_SOURCE_DIR}/otherplatforms/android/src/File.cpp
	)
else()
	list(APPEND PYROS_ENGINE_SOURCE
		${CMAKE_SOURCE_DIR}/src/Pyros3D/Core/File/File.cpp
	)
endif()

# Embind surface (WebAssembly) — compiled only under emcmake.
if (EMSCRIPTEN)
	list(APPEND PYROS_ENGINE_SOURCE
		${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/Bindings/PyrosEmbindEnums.cpp
		${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/Bindings/PyrosEmbindMath.cpp
		${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/Bindings/PyrosEmbind.cpp
		${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/Bindings/PyrosEmbindRender.cpp
		${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/Bindings/PyrosEmbindAssets.cpp
		${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/Bindings/PyrosEmbindPhysics.cpp
		${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/Bindings/PyrosEmbindPostFX.cpp
		${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/Bindings/PyrosEmbindAudio.cpp
		${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/Bindings/PyrosEmbindMisc.cpp
		${CMAKE_SOURCE_DIR}/src/Pyros3D/Utils/Bindings/PyrosEmbindUI.cpp
	)
endif()
